package Postulante;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * solucionando problemas con esta clase
 */
import javax.swing.JOptionPane;

public class InterfazRegistroPostulante extends javax.swing.JFrame {
    private String nombre;
    private String apellido;
    private String ci;
    private String correo;
    private String fechaNac;
    private String telefono;
    private String colegio;
    private String direccion;
    private String carrera;
    
    public InterfazRegistroPostulante() {
        initComponents();
        BtnImprimir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JButton();
        CasillaNombre = new javax.swing.JTextField();
        CasillaApellido = new javax.swing.JTextField();
        CasillaCI = new javax.swing.JTextField();
        CasillaCorreo = new javax.swing.JTextField();
        CasillaTelefono = new javax.swing.JTextField();
        CasillaDir = new javax.swing.JTextField();
        CasillaColegio = new javax.swing.JTextField();
        CasillaCarrera = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CasillaFecha = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        label1.setText("label1");

        label2.setText("label2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Postulantes");
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("NOMBRES:");

        jLabel2.setText("APELLIDOS:");

        jLabel3.setText("CORREO ELECTRONICO:");

        jLabel4.setText("CI:");

        jLabel5.setText("TELEFONO:");

        jLabel6.setText("COLEGIO:");

        jLabel7.setText("DIRECCION:");

        jLabel9.setText("CARRERA:");

        jLabel10.setText("FECHA DE NACIMIENTO:");

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnImprimir.setText("Imprimir");
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });

        CasillaCorreo.setToolTipText("");
        CasillaCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaCorreoActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(153, 153, 255));
        jLabel11.setText("LLENE LOS DATOS CON CUIDADO PARA SU REGISTRO ");
        jLabel11.setDoubleBuffered(true);

        CasillaFecha.setColumns(3);
        try {
            CasillaFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("dia/mes/año");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CasillaCarrera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(CasillaDir, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CasillaColegio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CasillaTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CasillaCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CasillaCI, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CasillaApellido, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CasillaNombre, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CasillaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(CasillaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CasillaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CasillaCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CasillaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CasillaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CasillaColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CasillaDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CasillaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CasillaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        nombre = CasillaNombre.getText();
        apellido = CasillaApellido.getText();
        ci = CasillaCI.getText();
        correo = CasillaCorreo.getText();
        telefono = CasillaTelefono.getText();
        colegio = CasillaColegio.getText();
        direccion = CasillaDir.getText();
        carrera = CasillaCarrera.getText();
        fechaNac = CasillaFecha.getText();
        
    if(nombre.isEmpty()){
        JOptionPane.showMessageDialog(this, "El campo Nombre es obligatorio.");
        return;
    }
    if(apellido.isEmpty()){
        JOptionPane.showMessageDialog(this, "El campo Apellido es obligatorio.");
        return;
    }
    if(ci.isEmpty() || !ci.matches("\\d+")){
        JOptionPane.showMessageDialog(this, "El CI es obligatorio");
        return;
    }
    if(correo.isEmpty() || !correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")){
        JOptionPane.showMessageDialog(this, "Debe ingresar un correo electrónico válido.");
        return;
    }
    if(telefono.isEmpty() || !telefono.matches("\\d{7,8}")){
        JOptionPane.showMessageDialog(this, "Debe ingresar un numero de telefono");
        return;
    }
    if(colegio.isEmpty()){
        JOptionPane.showMessageDialog(this, "El campo Colegio es obligatorio.");
        return;
    }
    if(direccion.isEmpty()){
        JOptionPane.showMessageDialog(this, "El campo Dirección es obligatorio.");
        return;
    }
    if(carrera.isEmpty()){
        JOptionPane.showMessageDialog(this, "El campo Carrera es obligatorio.");
        return;
    }
    if(fechaNac.equals("  /  /    ")){
    JOptionPane.showMessageDialog(this, "Debe ingresar la fecha de nacimiento.");
    return;
}

String[] partes = fechaNac.split("/");
try {
    int dia = Integer.parseInt(partes[0]);
    int mes = Integer.parseInt(partes[1]);
    int anio = Integer.parseInt(partes[2]);

    java.util.Calendar calendario = java.util.Calendar.getInstance();
    int anioActual = calendario.get(java.util.Calendar.YEAR);

    if(mes < 1 || mes > 12){
        JOptionPane.showMessageDialog(this, "Debe ingresar un mes valido.");
        return;
    }

    int[] diasPorMes = {31,28,31,30,31,30,31,31,30,31,30,31};
    if((anio % 4 == 0 && anio % 100 != 0) || (anio % 400 == 0)){
        diasPorMes[1] = 29; 
    }
    if(dia < 1 || dia > diasPorMes[mes-1]){
        JOptionPane.showMessageDialog(this, "Debe ingresar un dia valido");
        return;
    }

    if(anio > anioActual){
        JOptionPane.showMessageDialog(this, "El año de nacimiento no puede ser mayor al actual.");
        return;
    }

} catch(Exception e){
    JOptionPane.showMessageDialog(this, "Fecha de nacimiento inválida.");
    return;
}
    // Guardar en base de datos
    boolean guardado = LogicaPostulante.guardarDatosEstudiante(nombre, apellido, fechaNac, telefono, colegio, direccion, carrera, ci);

    if(guardado){
        BtnImprimir.setEnabled(true);  
    }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        GeneradorFormulario.generarPDF(nombre, apellido, ci, correo, fechaNac, telefono, colegio, direccion, carrera);
        limpiarCampos();
        BtnImprimir.setEnabled(false);
    }//GEN-LAST:event_BtnImprimirActionPerformed

    private void CasillaCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaCorreoActionPerformed
  private void limpiarCampos() {
        CasillaNombre.setText("");
        CasillaApellido.setText("");
        CasillaCI.setText("");
        CasillaCorreo.setText("");
        CasillaTelefono.setText("");
        CasillaColegio.setText("");
        CasillaDir.setText("");
        CasillaCarrera.setText("");
        CasillaFecha.setText("");
        
        
        nombre = "";
        apellido = "";
        ci = "";
        correo = "";
        telefono = "";
        colegio = "";
        direccion = "";
        carrera = "";
        fechaNac = "";
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JTextField CasillaApellido;
    private javax.swing.JTextField CasillaCI;
    private javax.swing.JTextField CasillaCarrera;
    private javax.swing.JTextField CasillaColegio;
    private javax.swing.JTextField CasillaCorreo;
    private javax.swing.JTextField CasillaDir;
    private javax.swing.JFormattedTextField CasillaFecha;
    private javax.swing.JTextField CasillaNombre;
    private javax.swing.JTextField CasillaTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
