/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Adminiatrador;

/**
 *
 * @author User
 */
import static Adminiatrador.CompraValoradoAD.registrarPagoValorado;
import static Adminiatrador.CompraValoradoAD.verificarRegistro;
import Adminiatrador.conexionPagoBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JButton;

public class InterfazAdmi extends javax.swing.JFrame {
    private boolean modoRegistrar = false; 

    private String ci1=null;

    
   public InterfazAdmi() {
        initComponents();
        jButton1.setText("Consultar");
        jButton1.setEnabled(true);
    }
    private boolean validarDocumento(String cedula) {
       if (cedula.isEmpty()) {
           JOptionPane.showMessageDialog(this, "El campo C.I. no puede estar vacío.");
           return false;
       }

       try {
           Integer.parseInt(cedula); 
       } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "C.I. debe contener solo números enteros.");
           return false;
       }

       return true;
   }
   
   
  private void Consultar() {
    String cedula = txtCI.getText().trim();
    if (cedula.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el C.I.");
        return;
    }


    try  {
        boolean existe=verificarRegistro(cedula);

        if (existe) {
            ci1=cedula;
            modoRegistrar = true;
            jButton1.setText("Registrar");   

            jButton1.setEnabled(true);
            
            JOptionPane.showMessageDialog(this,"Postulante encontrado.");
        } else {

            ci1=null;

            modoRegistrar = false;
            jButton1.setText("Consultar");
            jButton1.setEnabled(true);
            JOptionPane.showMessageDialog(this, "El postulante no está registrado.");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al consultar: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO COMPRA DE VALORADO");

        jLabel2.setText("C.I. DEL POSTULANTE:");

        txtCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIActionPerformed(evt);
            }
        });

        jButton1.setText("CONSULTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)

                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String cedula = txtCI.getText().trim();                                                                         
   if (!modoRegistrar) {
      if (!validarDocumento(cedula))
{
            return; 
        }
        Consultar();
    } else {
         boolean sepudo = registrarPagoValorado(ci1);  
         if(sepudo){
        JOptionPane.showMessageDialog(this,"Pago registrado correctamente." );
        }else{
           JOptionPane.showMessageDialog(this,"no se pudo registrar" );  
         }
        modoRegistrar = false;
        jButton1.setText("Consultar");
        txtCI.setText("");

    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCI;
    // End of variables declaration//GEN-END:variables
}
